### ISSUE TITLE
ERROR: database is locked

### ISSUE THREAD

**Issue by abbaszpro** [giovannicoppola/alfred-yaanki#1]
![image](https://user-images.githubusercontent.com/18553767/171410640-aa16329a-4acb-4a49-8781-6a9f79bba589.png)

Any ideas why?

Anki Version ⁨2.1.49 (dc80804a)⁩
macOS 12.3 (21E230)

**Comment by giovannicoppola** [comment]
sorry I missed this @manontop! Is Anki open? The workflow works only if the Anki app is closed
