### ISSUE TITLE
Close Alfred window once card is created

### ISSUE THREAD

**Issue by marlouis** [giovannicoppola/alfred-yaanki#2]
Daer giovannicoppola, 

Thank you for your great Workflow which I use everyday. Would it be possible to close the Alfred window once the card is created ? So I don't have to hit escape each time I create a card ? I joined a video -> [https://youtu.be/lWxo3ZbrBxc](url)

Regards;

**Comment by giovannicoppola** [comment]
I see what you mean. The idea was to create multiple cards at once, but I can add that as an option.

**Comment by giovannicoppola** [comment]
@marlouis for now, you can achieve that by deleting this object:
![image](https://user-images.githubusercontent.com/5774411/222697769-c28c0066-60f0-4acb-9e0f-ba18a76234c8.png)

**Comment by marlouis** [comment]
It works thank you so much ! (The video was not the right one indeed ^^-)
